function E = GreenStrainTensor(F,dof)
    if dof == 2
        E = [F(:,1)-1,(F(:,2)+F(:,3))/2,...
             (F(:,2)+F(:,3))/2,F(:,4)-1];
    elseif dof == 3
        E = [F(:,1)-1, (F(:,2)+F(:,4))/2, (F(:,3)+F(:,7))/2,...
             (F(:,2)+F(:,4))/2, F(:,5)-1, (F(:,6)+F(:,8))/2,...
             (F(:,3)+F(:,7))/2,(F(:,6)+F(:,8))/2,F(:,9)-1]; % green strain tensor
    end